//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senparc.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.APP_RedPackage_Activity_Award_Log = new HashSet<APP_RedPackage_Activity_Award_Log>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public bool EmailChecked { get; set; }
        public string Phone { get; set; }
        public bool PhoneChecked { get; set; }
        public string WeixinOpenId { get; set; }
        public string PicUrl { get; set; }
        public string HeadImgUrl { get; set; }
        public byte Sex { get; set; }
        public string QQ { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public int Type { get; set; }
        public System.DateTime ThisLoginTime { get; set; }
        public string ThisLoginIP { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastWeixinSignInTime { get; set; }
        public decimal Wallet { get; set; }
        public System.DateTime AddTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_RedPackage_Activity_Award_Log> APP_RedPackage_Activity_Award_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
