//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senparc.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_RedPackage_Activity_Award_Log
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int ActivityId { get; set; }
        public string AwardName { get; set; }
        public decimal Money { get; set; }
        public int State { get; set; }
        public string RegisterInfo { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual APP_RedPackage_Activity APP_RedPackage_Activity { get; set; }
    }
}
