//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senparc.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SenparcEntities : DbContext
    {
        public SenparcEntities()
            : base("name=SenparcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AdminUserInfo> AdminUserInfoes { get; set; }
        public virtual DbSet<APP_RedPackage_Activity> APP_RedPackage_Activity { get; set; }
        public virtual DbSet<APP_RedPackage_Activity_Award_Log> APP_RedPackage_Activity_Award_Log { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<SystemConfig> SystemConfigs { get; set; }
    }
}
